-- First, remove the table if it exists
drop table if exists customers;

-- Create the table anew
create table customers (
  id INTEGER primary key generated by default as identity,
  bookmark_name TEXT NOT NULL varying
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks(bookmark_name, id)
values
  ('page 2'),
  ('page 5'),
  ('page 10'),
  ('page 5'),
  ('page 4'),
  ('page 2'),
  ('page 6'),
  ('page 2'),
  ('page 12'),
  ('page 112'),
  ('page 222');
  

   For each attribute of a bookmark that you
    can think of, identify the data type,
     size, whether it can be null, if its a
      primary key and if a default value 
      makes sense.